import Head from "next/head"
import Navbar from "./Navigation/Navbar"
import Footer from "./Footer"
import { ReactNode, useEffect, useState } from "react"
import { useSession } from "next-auth/react"
import PrivacyandTermsModal from "./PrivacyandTermsModal"

type Props = {
	children?: ReactNode
	classNames?: string
}

export default function Layout({ children, classNames }: Props): JSX.Element {
	// const { data: session, status } = useSession()

	// const [acceptedPrivacyandTerms, setAcceptedPrivacyandTerms] =
	// 	useState<Boolean>(
	// 		session?.user?.acceptedPrivacy && session?.user?.acceptedTerms
	// 	)

	// useEffect(() => {
	// 	if (!acceptedPrivacyandTerms) {
	// 		document.body.style.overflow = "hidden"
	// 	}
	// }, [acceptedPrivacyandTerms])

	return (
		<>
			<Head>
				<title>Bountree - Startup Recruitment, but Good</title>
				<meta charSet="utf-8" />
				<meta name="viewport" content="initial-scale=1.0, width=device-width" />
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/favicon/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon/favicon-16x16espng"
				/>
			</Head>
			<Navbar />
			<main className={classNames}>{children}</main>
			{/* {!acceptedPrivacyandTerms && <PrivacyandTermsModal />} */}
			<Footer />
		</>
	)
}
